[platformio]
src_dir = .

[env:fw]
platform = ststm32@19.7.1
board = genericSTM32F103C8
framework = stm32cube
extra_scripts = post:scripts/export_hex.py

board_build.stm32cube.custom_config_header = yes
board_build.stm32cube.disable_embedded_libs = yes

upload_protocol = stlink
debug_tool = stlink
monitor_speed = 115200

build_type = release
build_flags =
    -D USE_HAL_DRIVER
    -D STM32F103xB
    -D W25Q64=1
    -Wno-unknown-pragmas
    -I Core
    -I Driver
    -I Main
    -I LR_driver
    -I LR_driver/src

build_src_filter =
    -<*>
    +<Main/main.c>
    +<Main/uart_protocol.c>
    +<Core/stm32f1xx_it.c>
    +<Core/stm32f1xx_clk.c>
    +<Core/syscalls_gcc.c>
    +<Driver/driver_usart.c>
    +<Driver/driver_spi.c>
    +<Driver/driver_key.c>
    +<Driver/driver_timer.c>
    +<LR_driver/UserConfig.c>
    +<LR_driver/src/sx126x.c>
    +<LR_driver/src/sx126x_hal.c>
